name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
#    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: azitmentor
        password: ${{ secrets.DOCKERPW }}
    
    - name: Build the Docker Image
      run: | 
          docker build ./samplewebapp/ --file samplewebapp/Dockerfile --tag nexquup/samplewebapp:latest
          docker push nexquup/samplewebapp:latest
